name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: self-hosted
    # runs-on: macos-10.15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Checkout repository conf
      uses: actions/checkout@v2
      with:
        repository: 'abcdesktopio/conf'
        path: conf

    # - name: Cache Vagrant boxes
    #  uses: actions/cache@v2
    #  with:
    #    path: ~/.vagrant.d/boxes
    #    key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
    #    restore-keys: |
    #      ${{ runner.os }}-vagrant-

    - name: Run script to list files
      run: |
         ls -la 
      shell: bash

    - name: Run vagrant up
      run: VAGRANT_VAGRANTFILE=Vagrantfile.docker vagrant up
      
    - name: Destroy vagrant 
      run: VAGRANT_VAGRANTFILE=Vagrantfile.docker vagrant destroy -f
